name: flodiff
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.8.5
  - cudatoolkit=10.2
  - numpy
  - matplotlib
  - ipykernel
  - pip
  - pip:
    - torch
    - torchvision
    - tqdm==4.64.0
    - opencv-python==4.6.0.66
    - h5py==3.6.0
    - wandb==0.12.18
    - efficientnet-pytorch
    - warmup-scheduler
    - diffusers==0.11.1
    - lmdb
    - vit-pytorch
    - positional-encodings
    - huggingface-hub==0.23.4
