project_name: flona
run_name: flona

# training setup
use_wandb: True # set to false if you don't want to log to wandb
train: True
batch_size: 128
epochs: 400
gpu_ids: [0] 
num_workers: 12
lr: 1e-4
optimizer: adamw
clipping: False #?
max_norm: 1.
scheduler: "cosine"
warmup: True 
warmup_epochs: 4
cyclic_period: 10
plateau_patience: 3
plateau_factor: 0.5
seed: 0
obs_type: image
goal_type: image
load_run: "flona/flona_2024_07_15_10_36_31"
# model params
vision_encoder: flona_vint
encoding_size: 256
obs_encoder: efficientnet-b0
attn_unet: False
cond_predict_scale: False
mha_num_attention_heads: 4
mha_num_attention_layers: 4
mha_ff_dim_factor: 4
down_dims: [64, 128, 256]

# diffusion model params
num_diffusion_iters: 10

# normalization for the action space
normalize: True

# context
context_size: 3 # 5
alpha: 1e-3

# action output params
len_traj_pred: 32
learn_angle: False

# dataset specific parameters
image_size: [96, 96] # width, height
datasets:

  # sacson:
  #   data_folder: /home/user/data/vis_nav/visualnav-transformer/datasets/sacson/
  #   train: /home/user/data/vis_nav/visualnav-transformer/train/vint_train/data/data_splits/sacson/train/
  #   test: /home/user/data/vis_nav/visualnav-transformer/train/vint_train/data/data_splits/sacson/test/
  #   end_slack: 3 # because many trajectories end in collisions
  #   goals_per_obs: 1
  #   negative_mining: True
  data_folder: /home/user/data/vis_nav/iGibson/igibson/dataset/Quantico_500
  end_slack: 3 # because many trajectories end in collisions
  goals_per_obs: 1
  waypoint_spacing: 1


# logging stuff
## =0 turns off
print_log_freq: 100 # in iterations
image_log_freq: 50 #0 # in iterations
num_images_log: 8 #0 
pairwise_test_freq: 0 # in epochs
eval_fraction: 0.25
wandb_log_freq: 10 # in iterations
eval_freq: 5 # in epochs